apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-nexus-dev
  namespace: argocd
  # TODO: Add sync policies annotations if required
spec:
  project: default
  source:
    repoURL: 'https://github.com/Manikandan23005/Microservice-Deployment-Monitoring-Platform.git'
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-nexus-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
