global:
  environment: "dev"
serviceName: "products"
replicaCount: 1
containerPort: 8000
image:
  repository: "products"
  tag: "latest"
  pullPolicy: "Never"
service:
  type: "ClusterIP"
  port: 8000
resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 80
ingress:
  enabled: false