apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-nexus.fullname" . }}-gateway
  labels:
    app: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.port }}
    protocol: TCP
    name: http
  selector:
    app: gateway
