apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service.devops-nexus.svc.cluster.local:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-service.devops-nexus.svc.cluster.local:3100
