apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '/home/satoru/Projects/Microservice-Deployment-Monitoring-Platform'
    targetRevision: HEAD
    path: helm/auth
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-nexus-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true