global:
  environment: "prod"
serviceName: "auth"
replicaCount: 3
containerPort: 8000
image:
  repository: "auth"
  tag: "latest"
  pullPolicy: "Never"
service:
  type: "ClusterIP"
  port: 8000
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
hpa:
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 75
ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "auth.devopsnexus.prod"
      paths:
        - path: "/"
          pathType: "Prefix"