global:
  environment: "dev"
serviceName: "auth"
replicaCount: 2
containerPort: 8000
image:
  repository: "auth"
  tag: "latest"
  pullPolicy: "Never"
service:
  type: "ClusterIP"
  port: 8000
resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 80
ingress:
  enabled: false