global:
  scrape_interval: 15s
  evaluation_interval: 15s

# TODO: Define Prometheus alerting rule files
# rule_files:
#   - "alert.rules.yml"

scrape_configs:
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: apiserver

  - job_name: 'devops-nexus-microservices'
    metrics_path: '/healthz' # TODO: Update to /metrics once endpoints are active
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - devops-nexus
