apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-nexus-sa
  namespace: devops-nexus
  annotations:
    # TODO: Add AWS IAM role mappings or Google Workload Identity service mappings
    # eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/devops-nexus-sa-role"
