global:
  environment: "dev"
serviceName: "frontend"
replicaCount: 1
containerPort: 3000
image:
  repository: "frontend"
  tag: "latest"
  pullPolicy: "Never"
service:
  type: "ClusterIP"
  port: 3000
resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 80
ingress:
  enabled: false