global:
  environment: "prod"
serviceName: "frontend"
replicaCount: 2
containerPort: 3000
image:
  repository: "frontend"
  tag: "latest"
  pullPolicy: "Never"
service:
  type: "ClusterIP"
  port: 3000
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 75
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "frontend.devopsnexus.prod"
      paths:
        - path: "/"
          pathType: "Prefix"